FROM dockerhub.planetek.it/node-bower-compass-grunt:4
LABEL maintainer.name="ilias ioannou" \
      maintainer.email="ioannou@planetek.gr"
	  
ARG branch

RUN git clone -b $branch https://teamEreticoTfs:hIEMK-i=d@tfs.planetek.it/Planetek%20Hellas/pkh111_EOSAI/_git/pkh111_EOSAI_Web_App
WORKDIR pkh111_EOSAI_Web_App/eosai-gui
RUN npm cache clean
RUN npm install --loglevel=silly
RUN bower install  --allow-root
WORKDIR ..
